services:
  db:
    image: pgvector/pgvector:pg17
    container_name: bhutan_db_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chador2003
      POSTGRES_DB: bhutan_stay
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: bhutan_redis_local
    command: redis-server --requirepass chador2003
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  

# docker exec -it bhutan_redis_local redis-cli -a chador2003